### ISSUE TITLE
Loading SA is suddenly much slower than before

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#140] opened 2015-07-14 12:49 UTC
As of the most recent commit, the app loads very slowly. At first I thought i t was brokem, because it was only displaying labels. 
![screen shot 2015-07-14 at 9 48 06 am](https://cloud.githubusercontent.com/assets/2263033/8673530/ae4df57c-2a0d-11e5-8237-7dbf0bf59aef.png)

**Comment by lkysow** [comment] 2015-07-21 07:25
For some reason it's taking a long time to receive the services data `compiled_AR.json` specifically from the server. Maybe changing the server config could fix it, that's all I know for now.

**Comment by PeaceGeeks** [comment] 2015-07-21 13:48
Today, it took 21 seconds for the page to load from a pretty decent internet connection. @tuckerbuchy @Jareechang - can one of you look at this?

**Comment by PeaceGeeks** [comment] 2015-07-21 13:50
It also took 24 seconds to switch to English.

**Comment by lkysow** [comment] 2015-07-24 06:58
Closing this, it should be fixed on the real installation and is therefore not a blocker for launch. Cannot reproduce locally and not worth debugging the issue on the dev server.

**Closed as completed by lkysow** 2015-07-24 06:58 UTC
Labels: bug, medium
