### ISSUE TITLE
Icons for service type not appearing on marker

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#135] opened 2015-07-10 04:21 UTC
![screen shot 2015-07-09 at 9 20 42 pm](https://cloud.githubusercontent.com/assets/2263033/8612116/6c3e8eb6-2680-11e5-9ca1-1e2ec96f327e.png)

**Comment by lkysow** [comment] 2015-07-21 07:29
I can't reproduce this. Which marker is it?

**Comment by PeaceGeeks** [comment] 2015-07-21 13:58
I can't reproduce this either now, tho it came up before after roaming on the site for a while. Will close for now, and will re-open if I can identify reproducable steps.

**Comment by PeaceGeeks** [comment] 2015-07-21 14:18
Closed too quickly. I was in the English desktop version and switched over to Arabic The summary circles (with numbers on the map) were also appearing out of sync. And I got this. 
![screen shot 2015-07-21 at 11 17 23 am](https://cloud.githubusercontent.com/assets/2263033/8802860/46ebb378-2f9a-11e5-96a9-f4ffdffcc044.png)

**Comment by PeaceGeeks** [comment] 2015-07-21 14:21
![screen shot 2015-07-21 at 11 19 11 am](https://cloud.githubusercontent.com/assets/2263033/8802971/aec9b4fe-2f9a-11e5-8f8c-53471a0dadfc.png)

**Comment by PeaceGeeks** [comment] 2015-07-21 14:36
Once this happens, it is persistent on the Arabic version (English seems fine). All the icons placements are off for the whole site. I need to clear my browser before it stops doing this.

**Comment by lkysow** [comment] 2015-07-22 05:52
Reproduced this and figured out it was the text direction in arabic.

**Comment by PeaceGeeks** [comment] 2015-07-22 06:07
Hi @lkysow - is this change merged? Because I can still reproduce it in Safari after clearing my cache. I am also getting the issue of double records (150 instead of 75) which used to happen only later - now its defaulting to that but to 75 on the EN version. And of course I 
![screen shot 2015-07-22 at 3 06 59 am](https://cloud.githubusercontent.com/assets/2263033/8819050/bfdb1f24-301e-11e5-95a6-beeb7e560589.png)

**Comment by lkysow** [comment] 2015-07-28 05:36
This is fixed and merged and deployed.

**Closed as completed by lkysow** 2015-07-28 05:36 UTC
Labels: bug, visual, low
