### ISSUE TITLE
Reading service record content on mobile is not intuitive

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#116] opened 2015-07-07 04:03 UTC
![img_3679](https://cloud.githubusercontent.com/assets/2263033/8538547/77f89f7c-2422-11e5-9f38-501f14dfed80.jpg)
![img_3680](https://cloud.githubusercontent.com/assets/2263033/8538545/77f48dd8-2422-11e5-9e22-fce2f70dff29.jpg)
![img_3681](https://cloud.githubusercontent.com/assets/2263033/8538546/77f657bc-2422-11e5-9e7e-9f0e1d6a09fe.jpg)

**Comment by cynthialee** [comment] 2015-07-07 04:10
@PeaceGeeks can you please describe what the issue is? I know that moving the content left to right isn't intuitive - is that what this ticket is?

**Comment by PeaceGeeks** [comment] 2015-07-07 04:14
correct - i wouldn't know it was there at all if it wasn't for me accidentally swiping.

**Comment by cynthialee** [comment] 2015-07-07 04:16
In that case, I would recommend that we just switch this to your suggestion of having the info appear in one column.

**Comment by PeaceGeeks** [comment] 2015-07-07 04:17
that works for me.

**Comment by cynthialee** [comment] 2015-07-07 04:25
As discussed, use #115 as a solution.

**Comment by PeaceGeeks** [comment] 2015-07-14 12:48
@Jareechang - this is still displaying incorrectly to me.  
![screen shot 2015-07-14 at 9 44 40 am](https://cloud.githubusercontent.com/assets/2263033/8673486/3f2945f2-2a0d-11e5-9662-c43c0ffcfa21.png)

**Comment by PeaceGeeks** [comment] 2015-07-14 12:51
Think there was a cache issue. Can we have the labels wrap as occurs on the desktop version?

**Comment by amyngai** [comment] 2015-07-17 02:38
it's fixed in the Search Branch. We just need to wait for it to be deployed :)

**Closed as completed** 2015-07-17 19:41 UTC
Labels: visual, high
